### ISSUE TITLE
wolfssl conflict with openssl in Lienoldiffconfig

### ISSUE THREAD

**Issue by fengFork** [kenzok8/litte#2]
Lienoldiffconfig 中需要把wolfssl去掉，或者把openssl去掉，二者打架。(openwrt的main branch会编译错误)

我是去掉wolfssl保留openssl，加了以下两句：

```
# CONFIG_PACKAGE_libustream-wolfssl is not set
# CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_libustream-wolfssl is not set
```

**Comment by kenzok8** [comment]
嗯，谢谢指正

kenzo wu

> 在 2021年10月5日，07:42，fengFork ***@***.***> 写道：
> 
> CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_libustream-wolfssl is not set

**Comment by fengFork** [comment]
我copy的代码，最前面的# 被github markdown当成控制字符了。
修改了以下，用代码块把代码包起来了。可以正确显示# 了
